import { useState } from 'react';
import { ArrowRight, BrainCircuit, Layers3, Sparkles, HelpCircle, Check, Github, Linkedin, Mail, Zap, BarChart3, GraduationCap } from 'lucide-react';
import { Link } from 'react-router-dom';

const features = [
  { icon: Layers3, title: 'Active Recall Cards', text: 'Instantly transform massive lecture notes into active-recall flashcards.' },
  { icon: BrainCircuit, title: 'Adaptive Practice Quizzes', text: 'Generate customized multi-choice questions with detailed explanation guides.' },
  { icon: Sparkles, title: 'Intelligent Revision Summaries', text: 'Get mnemonics, important formulas, and quick checklists automatically extracted.' },
];

const benefits = [
  { icon: Zap, title: 'Save Hours of Reviewing', desc: 'No more wasting time copying notes. Paste and let AI create study aids in 5 seconds flat.' },
  { icon: BarChart3, title: 'Track Your Performance', desc: 'Gauge your active recall known/review status and review detailed quiz results.' },
  { icon: GraduationCap, title: 'Designed for Exam Success', desc: 'Mnemonics, definitions, and common pitfalls cards help you retain details under pressure.' }
];

const testimonials = [
  { name: 'Sarah Jenkins', role: 'Medical Student', text: 'StudySpark completely changed how I revise anatomy. The flashcards auto-generation saves me hours of manual note-taking every single week!' },
  { name: 'Alex Rivera', role: 'Computer Science Major', text: 'The quiz explanation feature is incredibly helpful. It doesn’t just tell me I’m wrong, it explains the key concept in simple terms.' },
  { name: 'Chloe Chen', role: 'AP History Student', text: 'AP US History has so many details. The summaries generated by StudySpark organize mnemonics and terms in such an easy-to-read way.' }
];

const faqs = [
  { q: 'How does the study set generation work?', a: 'Just paste your study notes, essay draft, or textbook section. Our backend passes your material to Gemini 2.5 Flash which analyzes the content and formats it into rich flashcards, summaries, and multiple-choice quizzes.' },
  { q: 'Is there a limit to how much text I can paste?', a: 'You can paste up to 12,000 characters of notes at a time—which is approximately 2,000 words. This is plenty of space for a typical lecture or textbook chapter!' },
  { q: 'Can I bookmark flashcards for later review?', a: 'Yes! While reviewing your flashcards, you can bookmark key cards. They will be pinned and accessible during your study session.' },
  { q: 'How do active recall and spaced repetition help?', a: 'Active recall forces your brain to retrieve information rather than just passively reading it. Testing yourself with quizzes and cards creates stronger memory pathways for AP, university, or professional exams.' }
];

export function LandingPage() {
  const [openFaq, setOpenFaq] = useState(null);

  return (
    <div className="landing-page">
      {/* Hero Section */}
      <section className="hero">
        <p className="eyebrow"><Sparkles size={14} /> Your notes, made memorable</p>
        <h1>Study less.<br /><span>Remember more.</span></h1>
        <p className="hero-copy">Transform any study material into interactive flashcards, focused quizzes, and concise revision notes powered by Gemini 2.5 Flash.</p>
        <div className="hero-buttons">
          <Link className="primary-button" to="/workspace">Start studying <ArrowRight size={17} /></Link>
        </div>
      </section>

      {/* Feature Grid */}
      <section className="feature-grid" aria-label="StudySpark features">
        {features.map(({ icon: Icon, title, text }) => (
          <article className="feature-card" key={title}>
            <Icon size={20} />
            <h2>{title}</h2>
            <p>{text}</p>
          </article>
        ))}
      </section>

      {/* Why StudySpark? Section */}
      <section className="why-studyspark">
        <p className="kicker"><Zap size={14} /> High-Efficiency Revision</p>
        <h2>Why revise with StudySpark?</h2>
        <p className="section-description">We combine cognitive science methods with state-of-the-art AI to supercharge your memory retention.</p>

        <div className="benefits-grid">
          {benefits.map((b, idx) => {
            const Icon = b.icon;
            return (
              <article className="benefit-card" key={idx}>
                <span className="benefit-icon-wrapper"><Icon size={20} /></span>
                <h3>{b.title}</h3>
                <p>{b.desc}</p>
              </article>
            );
          })}
        </div>
      </section>

      {/* How it Works Section */}
      <section className="how-it-works">
        <p className="kicker"><GraduationCap size={14} /> Simple 3-step mastery</p>
        <h2>Revise in three simple steps</h2>

        <div className="steps-container">
          <article className="step-card">
            <span className="step-num">1</span>
            <h3>Paste Your Material</h3>
            <p>Paste lecture slides, chapters, vocabulary lists, or raw notes into the study console.</p>
          </article>
          <article className="step-card">
            <span className="step-num">2</span>
            <h3>AI Structures Study Set</h3>
            <p>Gemini auto-extracts exam tips, mnemonics, active-recall card decks, and adaptive quizzes.</p>
          </article>
          <article className="step-card">
            <span className="step-num">3</span>
            <h3>Study & Master</h3>
            <p>Test yourself with flashcard flips and multiple-choice options with instant correct justifications.</p>
          </article>
        </div>
      </section>

      {/* AI Mockup Section */}
      <section className="ai-powered-learning">
        <div className="ai-mockup-wrapper">
          <div className="ai-mockup-header">
            <span className="mockup-dot red"></span>
            <span className="mockup-dot yellow"></span>
            <span className="mockup-dot green"></span>
            <span className="mockup-title">AI Study Console</span>
          </div>
          <div className="ai-mockup-body">
            <div className="mockup-flashcard-preview">
              <span className="mockup-tag">Concept • Hard</span>
              <strong>How does Spaced Repetition enhance cognitive retrieval?</strong>
              <small>Click card to flip and reveal answer</small>
            </div>
            <div className="mockup-quiz-preview">
              <span>What is Spaced Repetition?</span>
              <div className="mockup-option correct"><Check size={14} /> Systematically reviewing details at increasing intervals</div>
              <div className="mockup-option">Reading the same chapter five times quickly</div>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="testimonials-section">
        <p className="kicker"><Sparkles size={14} /> Student Testimonials</p>
        <h2>Loved by university and school students</h2>
        <div className="testimonials-grid">
          {testimonials.map((t, idx) => (
            <article className="testimonial-card" key={idx}>
              <p className="testimonial-text">"{t.text}"</p>
              <div className="testimonial-user">
                <span className="user-avatar">{t.name[0]}</span>
                <div>
                  <h4>{t.name}</h4>
                  <p>{t.role}</p>
                </div>
              </div>
            </article>
          ))}
        </div>
      </section>

      {/* FAQ Section */}
      <section className="faq-section">
        <p className="kicker"><HelpCircle size={15} /> Frequently Asked Questions</p>
        <h2>Frequently Asked Questions</h2>
        <div className="faq-list">
          {faqs.map((faq, idx) => {
            const isOpen = openFaq === idx;
            return (
              <article key={idx} className={`faq-item ${isOpen ? 'is-open' : ''}`}>
                <button className="faq-question-btn" onClick={() => setOpenFaq(isOpen ? null : idx)}>
                  <span>{faq.q}</span>
                  <span className="faq-toggle-icon">{isOpen ? '−' : '+'}</span>
                </button>
                <div className="faq-answer">
                  <p>{faq.a}</p>
                </div>
              </article>
            );
          })}
        </div>
      </section>

      {/* Final CTA */}
      <section className="final-cta">
        <h2>Supercharge your exam preparation today.</h2>
        <p>Paste notes, revise key points, flip cards, and master quizzes.</p>
        <Link className="primary-button" to="/workspace">Get Started for Free <ArrowRight size={17} /></Link>
      </section>

      {/* Custom Footer */}
      <footer className="site-footer">
        <div className="footer-top">
          <div className="footer-brand">
            <Sparkles size={18} className="text-purple-400" />
            <span>StudySpark AI</span>
          </div>
          <p className="footer-tagline">Making study material memorable with generative AI.</p>
          <p className="footer-credits">Built with React, Express & Gemini 2.5 Flash</p>
        </div>
        <div className="footer-bottom">
          <div className="footer-copyright">
            <span>Made by <b className="font-semibold text-slate-200">Eram Fatima</b></span>
            <span className="footer-rights">© 2026 All Rights Reserved</span>
          </div>
          <div className="footer-links">
            <a href="https://github.com" target="_blank" rel="noopener noreferrer" className="footer-link-icon" aria-label="GitHub">
              <Github size={18} />
            </a>
            <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" className="footer-link-icon" aria-label="LinkedIn">
              <Linkedin size={18} />
            </a>
            <a href="mailto:eram@example.com" className="footer-link-icon" aria-label="Email">
              <Mail size={18} />
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}

