import { AlertTriangle, BookOpen, LayoutDashboard, Sparkles } from 'lucide-react';
import { useContext, useState } from 'react';
import { AppContext } from '../app/AppProvider';
import { ThemeToggle } from '../components/ui/ThemeToggle';
import { StudyInput } from '../features/generator/StudyInput';
import { Flashcards } from '../features/flashcards/Flashcards';
import { Quiz } from '../features/quiz/Quiz';
import { Summary } from '../features/summary/Summary';
import { useGeneration } from '../hooks/useGeneration';

export function WorkspacePage() { const [notes, setNotes] = useState(''); const [data, setData] = useState(null); const [tab, setTab] = useState('summary'); const [bookmarks, setBookmarks] = useState([]); const { sessions, setSessions } = useContext(AppContext); const { generate, status, error } = useGeneration(); const submit = async () => { const result = await generate(notes, tab); if (result) { setData(result); setTab('summary'); setSessions([{ id: crypto.randomUUID(), title: result.title, createdAt: Date.now(), data: result }, ...sessions].slice(0, 8)); } }; const restore = s => { setData(s.data); setTab('summary'); };
return <div className="workspace"><aside className="workspace-sidebar"><a href="/" className="side-brand"><Sparkles size={18}/> StudySpark</a><nav><button className="active"><LayoutDashboard size={17}/> Workspace</button><button><BookOpen size={17}/> My library</button></nav><div className="recent"><p>Recent sessions</p>{sessions.length ? sessions.slice(0, 5).map(s => <button key={s.id} onClick={() => restore(s)}>{s.title}</button>) : <span>Your saved sessions will appear here.</span>}</div><ThemeToggle /></aside><main className="workspace-main"><header className="workspace-header"><div><p className="kicker">Workspace</p><h1>Make your next revision count.</h1></div><ThemeToggle /></header><StudyInput notes={notes} onNotesChange={setNotes} onGenerate={submit} loading={status === 'loading'} />{status === 'loading' && <LoadingState />}{error && <div className="error-state"><AlertTriangle/><div><strong>That didn’t work this time.</strong><p>{error}</p></div><button className="secondary-button" onClick={submit}>Try again</button></div>}{data && status !== 'loading' && <StudyResults data={data} tab={tab} setTab={setTab} bookmarks={bookmarks} setBookmarks={setBookmarks}/>}</main></div>; }
function LoadingState() { return <section className="loading-state"><Sparkles size={22}/><h2>Finding the signal in your notes…</h2><p>Creating clear explanations, active-recall cards, and a focused quiz.</p><div className="skeleton-row"><i/><i/><i/></div></section>; }
function StudyResults({ data, tab, setTab, bookmarks, setBookmarks }) { const toggle = id => setBookmarks(items => items.includes(id) ? items.filter(x => x !== id) : [...items, id]); return <section className="results"><div className="result-heading"><div><p className="kicker">Ready to study</p><h2>{data.title}</h2><p>{data.description}</p></div><span className="set-count">{data.flashcards.length} cards · {data.quiz.length} questions</span></div><div className="tabs" role="tablist">{['summary','flashcards','quiz'].map(name => <button key={name} className={tab === name ? 'active' : ''} onClick={() => setTab(name)}>{name}</button>)}</div>{tab === 'summary' && <Summary data={data}/>} {tab === 'flashcards' && <Flashcards cards={data.flashcards} bookmarks={bookmarks} onBookmark={toggle}/>} {tab === 'quiz' && <Quiz questions={data.quiz}/>}</section>; }
